### ISSUE TITLE
Android library

### ISSUE THREAD

**Issue by woheller69** [open-meteo/geocoding-api#7]
I built an Android library, which opens a dialog fragment and searches for locations via your geocoding API.

It returns a city with name, country code, latitude, and longitude.

Maybe you want to link it somewhere

https://github.com/woheller69/OmGeoDialog

**Comment by patrick-zippenfenig** [comment]
Can you create a PR in the main project and add it to the list of SDKs? Thanks!

**Comment by patrick-zippenfenig** [comment]
PR merged in https://github.com/open-meteo/open-meteo/pull/325
